// Importing required view models for state management
import 'package:cunsumer_affairs_app/view_model/approved_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/category_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/change_password_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/commodity_details_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/dashboard_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/forget_pass_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/help_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/home_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/items_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/login_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/notification_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/otp_verify_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/productSurvey/product_survey_detail_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/profile_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/saved_survey_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/splash_view_model.dart';
import 'package:cunsumer_affairs_app/view_model/survey_list_view_model.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:hive_flutter/adapters.dart';
import 'package:provider/provider.dart';

import 'core/constants/app_routes.dart'; // Contains app route definitions
import 'firebase_options.dart'; // Firebase config generated by FlutterFire CLI
// Initial splash screen

Future<void> main() async {
  // Ensure that widget binding is initialized before any asynchronous operations
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with platform-specific options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize Hive for local data storage and open a box to store user data
  await Hive.initFlutter();
  await Hive.openBox('user_data');

  // Launch the main application widget
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      // Register all the view models using Provider package for state management
      providers: [
        ChangeNotifierProvider(create: (_) => ProfileViewModel()),
        ChangeNotifierProvider(create: (_) => SplashViewModel()),
        ChangeNotifierProvider(create: (_) => LoginViewModel()),
        ChangeNotifierProvider(create: (_) => HomeViewModel()),
        ChangeNotifierProvider(create: (_) => ForgotPasswordViewModel()),
        ChangeNotifierProvider(create: (_) => VerifyOtpViewModel()),
        ChangeNotifierProvider(create: (_) => ChangePasswordViewModel()),
        ChangeNotifierProvider(create: (_) => CategoryViewModel()),
        ChangeNotifierProvider(create: (_) => DashboardViewModel()),
        ChangeNotifierProvider(create: (_) => ProductSurveyViewModel()),
        ChangeNotifierProvider(create: (_) => SurveyListViewModel()),
        ChangeNotifierProvider(create: (_) => SurveySavedListViewModel()),
        // ChangeNotifierProvider(create: (_) => ProductListViewModel()),         commented out as it is not used in the app
        ChangeNotifierProvider(
            create: (_) => ProductSurveyDetailViewModel(context)),
        ChangeNotifierProvider(create: (_) => NotificationViewModel()),
        ChangeNotifierProvider(create: (_) => HelpViewModel()),
        ChangeNotifierProvider(create: (_) => SurveyDetailsViewModel()),
        ChangeNotifierProvider(create: (_) => ApprovedViewModel()),
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        theme:
            ThemeData(primarySwatch: Colors.green), // App's primary color theme
        initialRoute: AppRoutes.splashScreen, // Initial route when app starts
        routes: AppRoutes.pages, // Defined routes for navigation
      ),
    );
  }
}
